### ISSUE TITLE
Is this enterprise grade audit trail?

### ISSUE THREAD

**Issue by archenroot** [yantrashala/loopback-audit-trail#5]
Hi guys,

I have been searching for such kind of functionality with relationship to loopback.

We discuss this kind of stuff at:
https://github.com/strongloop/loopback/issues/2872
https://github.com/strongloop/loopback/issues/3116

In general my requirement is following:
- every pipeline (service flow) can log ENTRY(first step), EXIT(last step), ERROR(anything between these 2 on failure) events during processing.
- additionally to audit trail you usually need in SOA or microservices track much more than just transaction/corellation id, but complete set of inbound/outbound context (data + metadata)

Could you provide some description how your system works from high-level perspective?

Thanks.

**Comment by rjrahul** [comment]
Hi @archenroot ,

This package uses [bunyan](https://www.npmjs.com/package/bunyan) streams to perform logging. Primary idea was to log the execution of a resource and log the following

- IP Address
- URL and method
- Loopback class and method as event and sub event
- Method arguments and result/error (can be filtered using bunyan searializers)
- Userid if available else anonymous as user

Specifically, to your questions

> every pipeline (service flow) can log ENTRY(first step), EXIT(last step), ERROR(anything between these 2 on failure) events during processing.

It does not log ENTRY step but can be extended to do so (by adding a beforeRemote log. Although, my personal opinion is that it does not provide much of a use as response for both success and error is logged already.

> additionally to audit trail you usually need in SOA or microservices track much more than just transaction/corellation id, but complete set of inbound/outbound context (data + metadata)

It does log arguments and result/error of resource invocation and if correlation id is one of the parameters to remote method it would be logged.

**Comment by archenroot** [comment]
Hi @rjrahul,

thanks for your answers.

> It does not log ENTRY step but can be extended to do so (by adding a beforeRemote log. Although, my personal opinion is that it does not provide much of a use as response for both success and error is logged already.

Well, you are right ENTRY might not be of much use in sense where loopback does out-of-the box basic operations on data source and not "long-pipelines" like complex conversion, external service callouts in serial, etc. But having ENTRY/EXIT/ERROR is also very handy basic health check procedure or lets say it non-functional unit test. When there is ENTRY there should be always EXIT or ERROR. If there is only ENTRY point then something terrible happen to service processing (thread down, process down, database client stuck on connection, etc.) which could point you to the either bug in service or framework you use for service implementation. That is the purpose. It is easy to write health procedure to monitor "parity" of log messages.

We are discussing here usage of IBM microgateway for this audit trail functionality where I started thinking about it as kind of wrapper or auditing frontend: strongloop/loopback#2872

The main reason why it took my attention was capability of transform message and having some kind of built-in "middleware context"

> It does log arguments and result/error of resource invocation and if correlation id is one of the parameters to remote method it would be logged.

I see now and understand, so whatever is passed into method via some kind of parameter/filter/query, etc. will be capture and logged. Well my idea is to have quite large number (10-20, check the original thread at loopback) attributes which travel along with the message, later the audit usage is not only for some sanity and security check, but also for KPI report generation. I of course don't want to pass these 10-20 attributes from area called message header to the loopback, that is why I consider as well the microgateway as another auditing layer to be integrated to keep the loopback data services as light as possible. On the other hand I will introduce 2 HTTP call chain which could have negative impact on performance I think... so not sure about the right way to go.

Thanks again for suggestions.

**Comment by archenroot** [comment]
Just to add to this: This is only very small logging component, but not audit-trail as I see it, still could be useful for some small deployments.
